# Users schema
 
# --- !Ups
 
CREATE TABLE AULA (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    NOME varchar(255) NOT NULL,
    DESCRICAO varchar(255) NOT NULL,
    ID_SALA bigint(20) NOT NULL,
    NUMERO INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_SALA) REFERENCES SALA(ID)
);

CREATE TABLE SALA (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    NOME varchar(255) NOT NULL,
    DISCIPLINA varchar(255),
    DESCRICAO varchar(255),
    ESCOLA varchar(255),
    CODIGO varchar(255) NOT NULL,
    ID_PROFESSOR bigint(20) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR(ID)
);


CREATE TABLE PROFESSOR (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    NOME varchar(255) NOT NULL,
    TELEFONE varchar(255),
    DESCRICAO varchar(1000),
    EMAIL varchar(255),
    SENHA varchar(255),
    PRIMARY KEY (ID)
);

CREATE TABLE ALUNO (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    NOME varchar(255) NOT NULL,
    TELEFONE varchar(255),
    DESCRICAO varchar(1000),
    EMAIL varchar(255),
    SENHA varchar(255),
    PRIMARY KEY (ID)
);

CREATE TABLE SALA_ALUNO (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    ID_SALA bigint(20) NOT NULL,
    ID_ALUNO bigint(20) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_SALA) REFERENCES SALA(ID),
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID)
);

CREATE TABLE CAIXA_AULA (
    ID bigint(20) NOT NULL AUTO_INCREMENT,
    VALOR varchar(1000) NOT NULL,
    DESCRICAO varchar(255),
    ID_AULA bigint(20) NOT NULL,
    NUMERO INT,
    TIPO INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_AULA) REFERENCES AULA(ID)
);
 
# --- !Downs

DROP TABLE AULA;

DROP TABLE SALA;

DROP TABLE PROFESSOR;

DROP TABLE ALUNO;

DROP TABLE SALA_ALUNO;

DROP TABLE CAIXA_AULA;
